#!/usr/bin/env python

import sys
import os
import os.path

def main (argv):
    import sea
    import sea.commands


    cmds = [
            sea.commands.BMC,
            sea.commands.Pf,
            sea.commands.Smt,
            sea.commands.Clp,
            sea.commands.LfeSmt,
            sea.commands.LfeClp,
            sea.commands.Clang(),
            sea.commands.Seapp(),
            sea.commands.MixedSem(),
            sea.commands.Seaopt(),
            sea.commands.Seahorn(),
            sea.commands.SeahornClp(),
            sea.commands.FrontEnd,
            sea.commands.LegacyFrontEnd()
    ]


    cmd = sea.AgregateCmd('sea', 'SeaHorn Verification Framework', cmds)
    return cmd.main (argv)

if __name__ == '__main__':
    path = os.path.abspath (sys.argv[0])
    path = os.path.dirname(path)

    ## update system PATH to location of the package
    if os.path.isdir (path):
        os.environ['PATH'] = path + os.pathsep + os.environ['PATH']

    path = os.path.abspath (os.path.join(path, '..', 'lib', 'seapy'))
    if os.path.isdir (path): sys.path.insert(0, path)

    sys.exit (main (sys.argv[1:]))
