#!/usr/bin/env python

import sys
import os
import os.path

def main (argv):
    import sea
    import sea.commands


    cmds = [sea.commands.Bpf,
            sea.commands.CutLoops(),
            sea.commands.BndSmt,
            sea.commands.Pf,
            sea.commands.Smt,
            sea.commands.Clp,
            sea.commands.LfeSmt,
            sea.commands.LfeClp,
            sea.commands.Clang(),
            sea.commands.Seapp(),
            sea.commands.MixedSem(),
            sea.commands.Seaopt(),
            sea.commands.Seahorn(),
            sea.commands.SeahornClp(),
            sea.commands.FrontEnd,
            sea.commands.LegacyFrontEnd(),
            sea.commands.Crab(),
            sea.commands.feCrab,
            sea.commands.Unroll(),
            sea.commands.ClangPP,
            sea.commands.seaIncSmt,
            sea.commands.seaTerm,
            sea.commands.SeaAbc(),
            sea.commands.seaClangAbc,            
            sea.commands.LinkRt(),
            sea.commands.WrapMem(),
            sea.commands.Exe,
            sea.commands.SeaInspect(),
            sea.commands.feInspect
    ]


    cmd = sea.AgregateCmd('sea', 'SeaHorn Verification Framework', cmds)
    return cmd.main (argv)

if __name__ == '__main__':
    # unbuffered output
    sys.stdout = os.fdopen (sys.stdout.fileno (), 'w', 0)
    path = os.path.abspath (sys.argv[0])
    path = os.path.dirname(path)

    ## update system PATH to location of the package
    if os.path.isdir (path):
        os.environ['PATH'] = path + os.pathsep + os.environ['PATH']


    path = os.path.abspath (os.path.join(path, '..', 'lib', 'seapy'))
    if os.path.isdir (path): sys.path.insert(0, path)

    z3_path = os.path.abspath (os.path.join(path, '..', 'z3py'))

    if os.path.isdir (z3_path): sys.path.insert(0, z3_path)

    sys.exit (main (sys.argv[1:]))
